image:
repository: node-app-deployment-local
tag: latest

service:
type: NodePort
exposePort: 3001 // expose to node 
targetPort: 8080 // App server listening on this port
internalPort: 8081 // Internal exposed within the pod